redis:
  image: redis
  ports:
    - "6379:6379"

celery:
  build: .
  command: celery worker --app=app.celery
  volumes:
    - .:/code
  links:
    - redis

web:
  build: .
  command: python app.py
  volumes:
    - .:/code
  ports:
    - "5000:5000"
  links:
    - redis
