language: go
sudo: false

go:
    - 1.5

env:
    global:
        - BUILD_GOARCH=amd64

before_install:
    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr

install:
    - go get -t -v ./...

before_script:
    - echo "before script"

script:
    - go build
    - go test -v ./...

after_script:
    - echo "after script"

after_success:
    - bash ./ci/deploy-to-github.sh

after_failure:
    - echo "after failure"

before_deploy:
    - echo "before script"

deploy:
    - go build
    - go test -v ./...

after_deploy:
    - echo "after script"
